#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root /
#with a GET request (requesting a page) using curl,
#it must return a page that contains the string Hello World!
#As an answer file, write a Bash script that configures a
#new Ubuntu machine to respect above requirements

echo -e "Updating and installing Nginx.\n"
sudo ap-get update -y -qq && \
	sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\nCompleted.\n"
